---
include:
  - board: "nice_nano_2@2.0.0//zmk"
    shield: Pad15
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
  - board: "nice_nano_2@2.0.0//zmk"
    shield: settings_reset
